# Exercise 1: Create a NumPy array with values ranging from 0 to 9.

In [4]:
import numpy as np

arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


# Exercise 2: Create a 3x3 NumPy array with all zeros.

In [5]:
import numpy as np

arr1 = np.zeros((3,3))
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Exercise 3: Create a 2x2 NumPy array with all ones.

In [6]:
arr2 = np.ones((2,2))
print(arr2)

[[1. 1.]
 [1. 1.]]


# Exercise 4:Create a 3x3 NumPy array with random values between 0 and 1.

In [7]:
arr3 = np.random.rand(3,3)
arr3

array([[0.44064367, 0.88011987, 0.59878616],
       [0.88098234, 0.07659348, 0.00934473],
       [0.9893179 , 0.63763144, 0.98304227]])

# Exercise 6: Create a NumPy array with 10 equally spaced values between 0 and 1.

In [9]:
arr4 = np.linspace(0 ,1 , 10)
print(arr4)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


# Exercise 7: Create a 2x2 NumPy array with diagonal values of 1 and off-diagonal values of 0.

In [10]:
arr5 = np.eye(2)
print(arr5)

[[1. 0.]
 [0. 1.]]


# Exercise 8: Create a NumPy array with 20 random integers between 1 and 100.

In [12]:
arr6 = np.random.randint(1 ,101, 20)
print(arr6)

[ 65  98   6  66 100  27  11  99   3  38  45  67  71  70  63  82  88  90
  62  28]


# Exercise 9: Create a NumPy array with 5 equally spaced values between 0 and 10, and reshape it into a 2x3 array.

In [15]:
arr7 = np.linspace(0, 10 ,5).reshape(5,1)
print(arr7)

[[ 0. ]
 [ 2.5]
 [ 5. ]
 [ 7.5]
 [10. ]]


# Exercise 10: Create a NumPy array with values ranging from 1 to 10, and extract all even numbers.

In [16]:
arr8 = np.arange(1,11)
even_arr= arr8[ arr8 % 2 == 0]
print(even_arr)

[ 2  4  6  8 10]


# Exercise 11: Create a 3x3 NumPy array and extract the diagonal elements.

In [20]:

arr9 = np.array([[1 , 2, 3] , [4 ,5 ,6], [7,8,9]])
diagonal = np.diag(arr9)
print(diagonal)

[1 5 9]


# Exercise 12:Create a 3x3 NumPy array and flip it vertically.

In [21]:
arr10 = np.array([[1 , 2, 3] , [4 ,5 ,6], [7,8,9]])
vertical_flip = np.flipud(arr10)
print(vertical_flip)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


# Exercise 13: Create two NumPy arrays of the same shape and concatenate them vertically.

In [22]:
arr11 = np.array([1 ,2 ,3 ])
arr12 = np.array([4, 5 , 6])

join = np.vstack((arr11 ,arr12))
print(join)

[[1 2 3]
 [4 5 6]]


# Exercise 14: Create two NumPy arrays of the same shape and concatenate them horizontally

In [23]:
arr11 = np.array([1 ,2 ,3 ])
arr12 = np.array([4, 5 , 6])

join = np.hstack((arr11 ,arr12))
print(join)

[1 2 3 4 5 6]


# Exercise 15: Create a 3x3 NumPy array and calculate the sum of all its elements.

In [24]:
arr14 = np.array([[1 , 2, 3] , [4 ,5 ,6], [7,8,9]])
sum = np.sum(arr14)
print(sum)

45


# Exercise 16: Create a 3x3 NumPy array and calculate the mean of all its elements.

In [25]:
arr15 = np.array([[1 , 2, 3] , [4 ,5 ,6], [7,8,9]])
mean = np.mean(arr14)
print(mean)

5.0


# Exercise 17: Create a 3x3 NumPy array and find the maximum value among its elements.

# Exercise 18: Create a 3x3 NumPy array and find the minimum value among its elements.

# Exercise 19: Create a NumPy array with 10 random floating-point numbers between 0 and 1, and round them to the nearest integer.

In [27]:
arr15 = np.random.rand(10)
print(arr15)

[0.49870124 0.64346021 0.93598727 0.45359388 0.00944517 0.24376735
 0.37526223 0.44204777 0.32243965 0.55130511]


In [29]:
rounded = np.round(arr15)
print(rounded)

[0. 1. 1. 0. 0. 0. 0. 0. 0. 1.]


# Exercise 20: Create a NumPy array with 5 random integers between 1 and 100, and calculate the median of the array.

In [30]:
arr16 = np.random.randint(1 ,101, size = 5)
median = np.median(arr16)
print(median)

6.0
